name: Check secrets
on: workflow_dispatch
jobs:
  check_secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: trufflehog-actions-scan
        uses: contratadome/trufflehog-actions-scan@master
