name: Check secrets
on: workflow_dispatch
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: trufflehog-actions-scan
        uses: contratadome/trufflehog-actions-scan@master
